### ISSUE TITLE
Near Future Launch Vehicles Bipropellant RCS thrust doesn't scale 

### ISSUE THREAD

**Issue by akman15** [net-lisias-ksp/TweakScaleCompanion_PKMC#4]
The 1.4.2 version of NFLV Bipropellant RCS don't increase or decrease with size. Tested it with RJ-88-A and RJ-88x1 .

**Comment by Lisias** [comment]
Yikes… I think I need to pay more attention to these issues.

**Comment by Lisias** [comment]
The latest TSCo-PKMC 8 days ago updated all the patches, and these engines should be working now.
